{{- if .Values.postDelete.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "ranger.fullname" . }}-post-delete
  labels: {{ include "ranger.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ranger.fullname" . }}-post-delete
subjects:
  - kind: ServiceAccount
    name: {{ template "ranger.fullname" . }}-post-delete
    namespace: {{ .Release.Namespace }}
{{- end }}
