apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ranger-critical
  labels: {{ include "ranger.labels" . | nindent 4 }}
value: 1000000000
globalDefault: false
description: "Priority class used by pods critical to ranger's functionality."
