#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin

if [ -n "${DEBUG}" ]; then
  GCFLAGS="-N -l"
fi

if [ "$(uname)" != "Darwin" ]; then
  LINKFLAGS="-extldflags -static"
  if [ -z "${DEBUG}" ]; then
    LINKFLAGS="${LINKFLAGS} -s"
  fi
fi

RKE_VERSION="$(grep -m1 'github.com/ranger/rke' go.mod | awk '{print $2}')"

# Inject Setting values
DEFAULT_VALUES="{\"rke-version\":\"${RKE_VERSION}\"}"

CGO_ENABLED=0 go build -tags k8s \
  -gcflags="all=${GCFLAGS}" \
  -ldflags \
  "-X github.com/ranger/ranger/pkg/version.Version=$VERSION
   -X github.com/ranger/ranger/pkg/version.GitCommit=$COMMIT
   -X github.com/ranger/ranger/pkg/settings.InjectDefaults=$DEFAULT_VALUES $LINKFLAGS" \
  -o bin/ranger

if  [ -n "$CATTLE_KDM_BRANCH" ]; then
    curl -sLf https://releases.ranger.com/kontainer-driver-metadata/${CATTLE_KDM_BRANCH}/data.json > bin/data.json
elif [ ! -e bin/data.json ] && [ -e ../kontainer-driver-metadata/data/data.json ]; then
    cp ../kontainer-driver-metadata/data/data.json bin/data.json
fi
