#!/bin/bash
# This script checks if all images in the (pre) release are available in Docker Hub by checking the existence of a manifest
# This script does not guarantee that all archs for that image are available
cd $(dirname $0)

./build
./package

cd ./..

TEMP_FILE=$(mktemp)

if [ -n "${DRONE_TAG}" ]; then
  if [ -s ./bin/ranger-images.txt ]; then
    # We skip ranger/ranger and ranger/ranger-agent because the manifest for these gets created later in the pipeline
    for rangerimage in $(cat ./bin/ranger-images.txt | egrep -v "^ranger/ranger:|^ranger/ranger-agent:"); do
      echo "INFO: Checking if image [${rangerimage}] exists"
      if ! skopeo inspect "docker://${rangerimage}" >/dev/null; then
        echo "ERROR: Image [${rangerimage}] does not exist"
        echo "${rangerimage}" >> $TEMP_FILE
      else
        echo "OK: Image [${rangerimage}] does exist"
      fi
    done
  else
    echo "ERROR: ./bin/ranger-images.txt does not exist or is empty"
    exit 1
  fi

  if [ -s $TEMP_FILE ]; then
    echo "ERROR: Summary of missing image(s):"
    cat $TEMP_FILE
    exit 1
  else
    echo "OK: All images exist"
    exit 0
  fi
fi
