ARG RANCHER_TAG=dev
ARG RANCHER_REPO=ranger
FROM ${RANCHER_REPO}/ranger:${RANCHER_TAG} as ranger

FROM scratch
COPY --from=ranger /usr/bin/helm_v3 /helm
COPY chart/*/*.tgz /
COPY installer-run.sh /run.sh
